image: julia:1.7

variables:
  JULIA_DEPOT_PATH: "$CI_PROJECT_DIR/.julia"

# Cache notebooks in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - pluto_state_cache/
    - .julia/

# Install PlutoSlider Server
before_script:
- |
  julia --color=yes --threads=auto -e 'using Pkg;
            Pkg.activate(mktempdir());
            Pkg.add([
              Pkg.PackageSpec(name="PlutoSliderServer", version="0.3.2-0.3"),
            ]);
            import PlutoSliderServer;
            PlutoSliderServer.github_action(".";
              Export_cache_dir="pluto_state_cache",
              Export_baked_notebookfile=false,
              Export_baked_state=false,
              # more parameters can go here
            );'


test:
  stage: test
  script:
  - echo 'Test done.'
  except:
  - main


pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - main
