image: julia:1.7

variables:
  JULIA_DEPOT_PATH: "$CI_PROJECT_DIR/.julia"

# Cache notebooks and Julia packages in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}-julia-1.7
  paths:
    - pluto_state_cache/
    - .julia/artifacts/
    - .julia/packages/
    - .julia/compiled/

# Install PlutoSlider Server and run the notebooks
before_script:
- |
  julia --color=yes --threads=auto -e 'using Pkg;
            Pkg.activate(mktempdir());
            Pkg.add([
              Pkg.PackageSpec(name="PlutoSliderServer", version="0.3.2-0.3"),
            ]);
            import PlutoSliderServer;
            PlutoSliderServer.export_directory(".";
              Export_cache_dir="pluto_state_cache",
              Export_baked_notebookfile=false,
              Export_baked_state=false,
              # more parameters can go here
            );'


test:
  stage: test
  script:
  - echo 'Test done.'
  except:
  - main


pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  - apt-get update -qq && apt-get install gzip brotli -qqy --no-install-recommends
  - find public -type f -exec gzip -f -k {} \; -exec brotli -f -k {} \; || echo 'Compression failed. Skipping...'
  artifacts:
    paths:
    - public
  only:
  - main
